version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: andi_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: andi_backend
    environment:
      - NODE_ENV=production
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET:-dev-secret}
      - CREDENTIALS_ENCRYPTION_KEY=${CREDENTIALS_ENCRYPTION_KEY:-dev-dev-dev-dev-dev-dev-dev-dev-0000}
      - DATABASE_PATH=/data/andi.sqlite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - backend_data:/data
    ports:
      - "4000:4000"
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:4000
    container_name: andi_frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  backend_data:
  redis_data:
